version: "3.7"
version: "2.2"
services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    working_dir: /miso/PlannerMiso
    command: [nix-shell, -A, env, default.nix, --run, "cabal configure --ghcjs; ag -l | (ENTR_INOTIFY_WORKAROUND=1 entr sh -c 'cabal build')"]
    volumes:
      - ../PlannerMiso:/miso/PlannerMiso/
